### ISSUE TITLE
regions.json, 广东省-中山市, 东莞市, 缺下级

### ISSUE THREAD

**Issue by Supposer** [Instapp/china-regions#9]
regions.json, 广东省-中山市, 东莞市, 缺下级

{
        "code": "441900",
        "name": "东莞市"
      },
      {
        "code": "442000",
        "name": "中山市"
      },
      {
        "code": "445100",
        "name": "潮州市",
        "districts": [
          {
            "code": "445102",
            "name": "湘桥区"
          },
          {
            "code": "445103",
            "name": "潮安区"
          },
          {
            "code": "445122",
            "name": "饶平县"
          }
        ]
      },

**Comment by Supposer** [comment]
民政局官网也没有, 
但中山市和东莞市, 确实有下级镇街, 
令人费解, 只能自行百度添加

**Comment by acathur** [comment]
@Supposer 核实了一下，确实这个情况。项目暂时还是以官方数据、结构层级为准。
